### PR TITLE
Added check_transfer method and a working CA cert bundle

### PR DESCRIPTION
**Pull request by shawnsi**
I was having SSL issues without the CA cert change.  Also added a check_transfer method that I'm using in https://github.com/shawnsi/opensrs-cli.  Thought I'd see if you wanted to pull these in.

### CODE REVIEW

**Comment by borgstrom** [comment]
Hi @shawnsi, sorry I totally missed this pull request.

We'll get this reviewed and merged today. Thanks!

**Comment by borgstrom** [comment]
I've reviewed your changes and I don't agree with distributing the whole `cacerts.pem` file with this module, but I do see the problem since this doesn't work under httplib2 0.7+.

Based on the comments in [httplib2 issue 170](http://code.google.com/p/httplib2/issues/detail?id=170) I'm going to add certifi as a dependency and use it instead of distributing our own copy of the certs.

**Comment by shawnsi** [comment]
Sounds like a better approach to me.  Are you going to include the check_transfer method I added?

**Comment by borgstrom** [comment]
Absolutely :)

New version coming up to github & the cheeseshop in a few moments.

**Comment by borgstrom** [comment]
Certificate's should work in httplib > 0.7 now and the `check_transfer` method has been added.

Feel free to re-open if there's still an issue for you.

Thanks!

**Comment by borgstrom** [comment]
PS. 0.1.4 is up on the cheeseshop too: http://pypi.python.org/pypi/OpenSRS/

**Comment by shawnsi** [comment]
Awesome!  Now I can simplify deps for https://github.com/shawnsi/opensrs-cli.

If you could spare a few minutes for review I'd appreciate any feedback you have on that project.

Thanks!

**Pull request closed without merging**
